version: "3.8"

services:

  puma:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
      - "bundle_path:/bundle"
      - "node_modules:/app/node_modules/"
    environment:
      - BUNDLE_PATH=/bundle/vendor
      - RAILS2DOCKER_DATABASE_HOST=postgres
      - RAILS2DOCKER_DATABASE_USERNAME=postgres
      - RAILS2DOCKER_DATABASE_PASSWORD=postgress

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  bundle_path:
  node_modules:
  postgres_data:
